Experiment - 2 (Linear Discriminant Analysis)

---

Name : Shruti Hore

PRN : 24070126172

---

## Linear Discriminant Analysis (LDA)

- a supervised machine learning and statistical technique used primarily for classification and dimensionality reduction

- it projects high dimensional data onto a lower dimensional space while maximizing the class separability. (2D or more to 1D)

- criteria used by LDA to create a new axis :
  - **maximizes** the distance between means of two classes and
  - **minimizes** the variation within each class

# With Library

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.decomposition import PCA

In [ ]:
# Load taxi dataset
taxi_df = sns.load_dataset('taxis')
taxi_df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
taxi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

In [ ]:
taxi_df.describe()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total
count,6433,6433,6433.000000,6433.000000,6433.000000,6433.00000,6433.000000,6433.000000
mean,2019-03-16 08:31:28.514223616,2019-03-16 08:45:49.491217408,1.539251,3.024617,13.091073,1.97922,0.325273,18.517794
min,2019-02-28 23:29:03,2019-02-28 23:32:35,0.000000,0.000000,1.000000,0.00000,0.000000,1.300000
25%,2019-03-08 15:50:34,2019-03-08 16:12:51,1.000000,0.980000,6.500000,0.00000,0.000000,10.800000
50%,2019-03-15 21:46:58,2019-03-15 22:06:44,1.000000,1.640000,9.500000,1.70000,0.000000,14.160000
75%,2019-03-23 17:41:38,2019-03-23 17:51:56,2.000000,3.210000,15.000000,2.80000,0.000000,20.300000
max,2019-03-31 23:43:45,2019-04-01 00:13:58,6.000000,36.700000,150.000000,33.20000,24.020000,174.820000
std,NaN,NaN,1.203768,3.827867,11.551804,2.44856,1.415267,13.815570

In [ ]:
# check for missing values
taxi_df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [ ]:
# Drop missing values
taxi_df = taxi_df.dropna()

In [ ]:
taxi_df.isnull().sum()

pickup             0
dropoff            0
passengers         0
distance           0
fare               0
tip                0
tolls              0
total              0
color              0
payment            0
pickup_zone        0
dropoff_zone       0
pickup_borough     0
dropoff_borough    0
dtype: int64

In [ ]:
LE = LabelEncoder()
taxi_df['payment'] = LE.fit_transform(taxi_df['payment'])

### Feature Selection

In [ ]:
# Select features for classification
X = taxi_df[['fare', 'distance', 'pickup_borough', 'dropoff_borough']]
X = pd.get_dummies(X, drop_first=True)

y = taxi_df['payment']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.25,
                                                    random_state=67)

In [ ]:
SS = StandardScaler()
X_train_scaled = SS.fit_transform(X_train)
X_test_scaled = SS.transform(X_test)

### Accuracy with and without LDA

In [ ]:
RFC = RandomForestClassifier(n_estimators=100,
                             random_state=69)
RFC.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=69)

In [ ]:
y_pred = RFC.predict(X_test_scaled)
print("Accuracy on raw data =", metrics.accuracy_score(y_test, y_pred))

Accuracy on raw data = 0.6614123581336696

In [ ]:
LDA = LinearDiscriminantAnalysis(n_components=1)
X_train_lda = LDA.fit_transform(X_train_scaled, y_train)
X_test_lda = LDA.transform(X_test_scaled)

RFC.fit(X_train_lda, y_train)

y_pred_lda = RFC.predict(X_test_lda)
print("Accuracy using LDA (1 component) =", metrics.accuracy_score(y_test, y_pred_lda))

Accuracy using LDA (1 component) = 0.6305170239596469

In [ ]:
print(f"Accuracy on raw data = {metrics.accuracy_score(y_test, y_pred):.4f}")
print(f"Accuracy using LDA (1 component) = {metrics.accuracy_score(y_test, y_pred_lda):.4f}")

Accuracy on raw data = 0.6614
Accuracy using LDA (1 component) = 0.6305

The **decrease in accuracy** indicates that dimensionality reduction led to **information loss**.

Since the Taxi dataset may not satisfy LDA assumptions such as linear separability and equal covariance, reducing the data to one dimension reduced the discriminative power of the model.

Therefore, LDA did not improve classification performance.

In [ ]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix WITHOUT LDA")
print(confusion_matrix(y_test, y_pred))

print("Confusion Matrix WITH LDA")
print(confusion_matrix(y_test, y_pred_lda))

Confusion Matrix WITHOUT LDA
[[131 326]
 [211 918]]
Confusion Matrix WITH LDA
[[127 330]
 [256 873]]

# Without Library (Manual Implementation)

### Steps :
1. Calcualte the mean vectors for each class
2. Compute the covariance of each class
3. Compute the Within-Class Scatter Matrix (SW)
4. Compute the Between-Class Scatter Matrix (SB)
5. Find eigen values and choose the top eigen value
6. Find eigen vectors
7. Find the dot prodect of data points with eigen vectors

Assumption:

X → feature matrix (numeric only)

y → binary class (0 and 1)

In [ ]:
taxi_df['fare_class'] = (taxi_df['total'] > taxi_df['total'].median()).astype(int)

0 → Low fare

1 → High fare

In [ ]:
numeric_cols = ['passengers', 'distance', 'fare', 'tip', 'tolls', 'total']

X = taxi_df[numeric_cols].values
y = taxi_df['fare_class'].values

In [ ]:
print(X.shape)
print(X.dtype)

(6341, 6)
float64

In [ ]:
numeric_cols = ['passengers', 'distance', 'fare', 'tip', 'tolls']

In [ ]:
X = taxi_df[numeric_cols].values
y = taxi_df['fare_class'].values

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
# Separate Classes
X0 = X[y == 0]
X1 = X[y == 1]

In [ ]:
# Compute Mean Vectors
mu0 = np.mean(X0, axis=0)
mu1 = np.mean(X1, axis=0)

@ operator means matrix multiplication.

In [ ]:
# Compute Within-Class Scatter Matrix
S0 = np.zeros((X.shape[1], X.shape[1]))
for x in X0:
    diff = (x - mu0).reshape(-1,1)
    S0 += diff @ diff.T

S1 = np.zeros((X.shape[1], X.shape[1]))
for x in X1:
    diff = (x - mu1).reshape(-1,1)
    S1 += diff @ diff.T

SW = S0 + S1
SW

array([[6336.82100502,  -50.25143447, -102.94779975,   47.70262793,
         -56.27844335],
       [ -50.25143447, 4611.75293256, 4034.4398936 , 1693.96303898,
        3300.39232159],
       [-102.94779975, 4034.4398936 , 4081.74633284, 1567.84369266,
        3030.41037876],
       [  47.70262793, 1693.96303898, 1567.84369266, 5317.19976546,
        2034.91611192],
       [ -56.27844335, 3300.39232159, 3030.41037876, 2034.91611192,
        5995.77852807]])

In [ ]:
# Compute Between-Class Scatter Matrix
mean_diff = (mu1 - mu0).reshape(-1,1)
SB = mean_diff @ mean_diff.T
SB

array([[0.00263674, 0.05363646, 0.06130757, 0.04127045, 0.02396517],
       [0.05363646, 1.09107025, 1.24711553, 0.83952146, 0.48749828],
       [0.06130757, 1.24711553, 1.42547847, 0.95959014, 0.55722047],
       [0.04127045, 0.83952146, 0.95959014, 0.64596783, 0.37510442],
       [0.02396517, 0.48749828, 0.55722047, 0.37510442, 0.21781785]])

In [ ]:
# Solve Eigenvalue Problem
SW_inv = np.linalg.pinv(SW)

matrix = SW_inv @ SB

eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [ ]:
# Select Top Eigenvector
idx = np.argsort(abs(eigenvalues))[::-1]

W = eigenvectors[:, idx[0]]
W

array([-0.02311615+0.j,  0.31643853+0.j, -0.90833879+0.j, -0.17471268+0.j,
        0.20911341+0.j])

In [ ]:
# Project Data
X_lda = X @ W
X_lda

array([ 0.32914084+0.j,  0.58872425+0.j,  0.25167716+0.j, ...,
       -0.05821324+0.j,  0.53207732+0.j, -0.24672662+0.j])

In [ ]:
# Classification After Projection
m0 = W @ mu0
m1 = W @ mu1

threshold = (m0 + m1) / 2

y_pred = (X_lda > threshold).astype(int)

In [ ]:
# Accuracy
accuracy = np.mean(y_pred == y)
print("Manual LDA Accuracy:", accuracy)

Manual LDA Accuracy: 0.14303737580823214